### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bvarwig**

### CODE REVIEW

**Comment by bvarwig** [comment]
please update the readme.md file

**Comment by bvarwig** [comment]
please do similar stuff

**Review by snoeber — CHANGES_REQUESTED** [review]
Hi,
thanks for working on this - please correct the typo at the header: Tiny World SAP HANA XSA Excample 
Excample is wrong..

Thanks,
kc

**Review by snoeber — APPROVED** [review]
thanks

**Pull request merged**
